package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.industrialmessagesbridge.dataBaseData.LabelOne;
import com.example.administrator.industrialmessagesbridge.dataBaseData.LableTwo;

import com.aserbao.aserbaosandroid.functions.database.greenDao.db.LabelOneDao;
import com.aserbao.aserbaosandroid.functions.database.greenDao.db.LableTwoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig labelOneDaoConfig;
    private final DaoConfig lableTwoDaoConfig;

    private final LabelOneDao labelOneDao;
    private final LableTwoDao lableTwoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        labelOneDaoConfig = daoConfigMap.get(LabelOneDao.class).clone();
        labelOneDaoConfig.initIdentityScope(type);

        lableTwoDaoConfig = daoConfigMap.get(LableTwoDao.class).clone();
        lableTwoDaoConfig.initIdentityScope(type);

        labelOneDao = new LabelOneDao(labelOneDaoConfig, this);
        lableTwoDao = new LableTwoDao(lableTwoDaoConfig, this);

        registerDao(LabelOne.class, labelOneDao);
        registerDao(LableTwo.class, lableTwoDao);
    }
    
    public void clear() {
        labelOneDaoConfig.clearIdentityScope();
        lableTwoDaoConfig.clearIdentityScope();
    }

    public LabelOneDao getLabelOneDao() {
        return labelOneDao;
    }

    public LableTwoDao getLableTwoDao() {
        return lableTwoDao;
    }

}
