package com.aserbao.aserbaosandroid.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.industrialmessagesbridge.dataBaseData.LableTwo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LABLE_TWO".
*/
public class LableTwoDao extends AbstractDao<LableTwo, Long> {

    public static final String TABLENAME = "LABLE_TWO";

    /**
     * Properties of entity LableTwo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LableOneId = new Property(1, String.class, "lableOneId", false, "LABLE_ONE_ID");
        public final static Property LableTwoId = new Property(2, String.class, "lableTwoId", false, "LABLE_TWO_ID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
    }


    public LableTwoDao(DaoConfig config) {
        super(config);
    }
    
    public LableTwoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LABLE_TWO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LABLE_ONE_ID\" TEXT," + // 1: lableOneId
                "\"LABLE_TWO_ID\" TEXT," + // 2: lableTwoId
                "\"NAME\" TEXT);"); // 3: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LABLE_TWO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LableTwo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String lableOneId = entity.getLableOneId();
        if (lableOneId != null) {
            stmt.bindString(2, lableOneId);
        }
 
        String lableTwoId = entity.getLableTwoId();
        if (lableTwoId != null) {
            stmt.bindString(3, lableTwoId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LableTwo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String lableOneId = entity.getLableOneId();
        if (lableOneId != null) {
            stmt.bindString(2, lableOneId);
        }
 
        String lableTwoId = entity.getLableTwoId();
        if (lableTwoId != null) {
            stmt.bindString(3, lableTwoId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LableTwo readEntity(Cursor cursor, int offset) {
        LableTwo entity = new LableTwo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // lableOneId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lableTwoId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LableTwo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLableOneId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLableTwoId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LableTwo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LableTwo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LableTwo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
